config/routes.rb
Authuser::Application.routes.draw do
  root :to => "home#index"
  match '/profiles/dashboard' => 'profiles#dashboard', :as => :user_root

  devise_for :users, :path_names => {:sign_in => "login", :sign_out => "logout"}, :path => 'd'

  resources :profiles, :only => [:dashboard]

  namespace :admin do
    match '/' => 'users#index'
    resources :users
  end

  resources :posts

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user
    if user.role? :admin
      can :manage, :all
    elsif user.role? :registered
      can :manage, Post do |post|
        # true
        post.user_id == user.id
      end
      # can :new, Post, true
    else
      can :read, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin_ability.rb
class AdminAbility
  include CanCan::Ability
  def initialize(user)
    if user.role? :admin
      can :manage, :all
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
  attr_accessible :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  before_save :setup_role

  has_and_belongs_to_many :roles
  has_many :posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :role_ids

  def role?(role)
      return !!self.roles.find_by_name(role.to_s.camelize)
  end

  # Default role is "Registered"
  def setup_role 
    if self.role_ids.empty?     
      self.role_ids = [2] 
    end
  end

end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  layout "admin"
  before_filter :verify_admin

  def verify_admin
    :authenticate_user!
    redirect_to root_url unless has_role?(current_user, 'admin')
  end

  def current_ability
    @current_ability ||= AdminAbility.new(current_user)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  load_and_authorize_resource
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user.attributes = params[:user]
    @user.role_ids = params[:user][:role_ids] if params[:user]
    @user = User.new(params[:user])
    respond_to do |format|
      if @user.save
        flash[:notice] = flash[:notice].to_a.concat @user.errors.full_messages
        format.html { redirect_to admin_users_path, :notice => 'User was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        flash[:notice] = flash[:notice].to_a.concat @user.errors.full_messages
        format.html { render :action => "new"}
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    if params[:user][:password].blank?
        params[:user].delete(:password)
        params[:user].delete(:password_confirmation)
    end
 
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to admin_users_path, :notice => 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  def has_role?(current_user, role)
    return !!current_user.roles.find_by_name(role.to_s.camelize)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, :notice => 'Post was successfully created.' }
        format.json { render :json => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, :notice => 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_user!

  def dashboard
    @user = User.find(current_user.id)
    if @user.role? :admin
      redirect_to admin_users_path, :notice => "Aloah Admin!"
    else
      respond_to do |format|
        format.html # dashboard.html.erb
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/users/_form.html.erb
<div class="control-group">
   <%= f.label :email, t("activerecord.attributes.user.email", :default => "Email"), :class => 'control-label' %>
  <div class="input">
    <%= f.text_field :email, :class => 'text_field' %>
  </div>
</div>

<div class="control-group">
   <%= f.label :password, t("activerecord.attributes.user.password", :default => "password"), :class => 'control-label' %>
  <div class="input">
    <%= f.password_field :password, :class => 'password_field' %>
  </div>
</div>
<div class="control-group">
   <%= f.label :Password, t("activerecord.attributes.user.password_confirmation", :default => "password_confirmation"), :class => 'control-label' %>
  <div class="input">
    <%= f.password_field :password_confirmation, :class => 'password_field' %>
  </div>
</div>

<% for role in Role.find(:all) %> 
  <div class ="control-group">
   <%= f.label role.name , :class => 'control-label' %>
      <div class="controls">
        <%= check_box_tag "user[role_ids][]", role.id, @user.roles.include?(role) %> 
      </div> 
  </div>
<% end %>


<div class="form-actions">
  <button class="btn primary" type="submit">Save</button> or
	<%= link_to "Cancel", admin_users_path %>
</div>

app/views/admin/users/edit.html.erb
<%= form_for [:admin, @user], :url => admin_user_path(@user), :html => { :class => "form-horizontal", :id => "edit_user" } do |f| -%>
  <input name="_method" type="hidden" value="put" />
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/admin/users/index.html.erb
<h1>Users</h1>
<table class="table table-striped">
 <thead>
  <tr>
    <th>ID</th>
        <th>
      <%= t("activerecord.attributes.user.email", :default => t("activerecord.labels.email", :default => "Email")) %>
    </th>
        <th>Created at</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| -%>
   <tr>
    <td><%= user.id %></td>
        <td><%= link_to user.email, admin_user_path(user) %>
    </td>
        <td><%= user.created_at %></td>
    <td>
      <%= link_to "Show", admin_user_path(user) %>
      <%= link_to "Edit", edit_admin_user_path(user) %>
      <%= link_to "Destroy", admin_user_path(user), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
    </td>
    </tr>
    <% end -%>
   </tbody>
</table>

<%= link_to "New", new_admin_user_path, :class => 'btn btn-primary' %>

app/views/admin/users/new.html.erb
<%= form_for [:admin, @user], :url => admin_users_path, :html => { :class => :form } do |f| -%>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/admin/users/show.html.erb
<label class="label"><%= t("activerecord.attributes.user.email", :default => t("activerecord.labels.email", :default => "Email")) %>:</label>
<p><%= @user.email %></p>

<div class="form-actions">
<%= link_to "Back", admin_users_path, :class => 'btn'  %>
<%= link_to "Edit", edit_admin_user_path(@user), :class => 'btn' %>
<%= link_to "Delete", admin_user_path(@user), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn' %>
</div>

app/views/home/index.html.erb
<h1>Authorization and users management example</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Authuser</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%- flash.each do |name, msg| -%>
  <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
<%- end -%>

<% if user_signed_in? %>
  <% #link_to "My Profile", user_root_path%>
  <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>  
<%else%>
  <%= link_to('Login', new_user_session_path) %>  
  <%= link_to('Register', new_user_registration_path, :method=>'delete') %>  
<%end%>	

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Authuser</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%- flash.each do |name, msg| -%>
  <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
<%- end -%>


<% if user_signed_in? %>
  <%= link_to "My Profile", user_root_path%>
  <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>  
<%else%>
  <%= link_to('Login', new_user_session_path) %>  
  <%= link_to('Register', new_user_registration_path) %>  
<%end%>	

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/profiles/dashboard.html.erb
Hello User Id: <%= @user.id%>, here you can  <%= link_to "Edit your profile", edit_user_registration_path(current_user)%>